#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine
# to respect below requirements
# 	The redirection must be a “301 Moved Permanently”

# Check for updates
apt-get -y update

# Installs nginx
apt -y install nginx

# Add firewall for HTTP
# ufw allow 'Nginx HTTP'

# Add firewall for OpenSSH
# ufw allow 'OpenSSH'

# Enable the firewall
# ufw enable

# Changes the root page to contain the stril 'Hello World!'
echo "Hello World!" > /var/www/html/index.html

sudo sed -i '53i\location =  /redirect_me { return 301 http://youtube.com;}' /etc/nginx/sites-enabled/default

# Start the nginx service
# Start the nginx service
if [ "$(pgrep nginx)" ]; then
        service nginx restart
else
        service nginx start
fi
