#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine
# to respect below requirements
# 	The redirection must be a “301 Moved Permanently”

# Check for updates
apt-get -y update

# Installs nginx
apt -y install nginx

# Changes the root page to contain the stril 'Hello World!'
echo "Hello World!" > /var/www/html/index.html

# Create symboliclink between sites-available and sites-enabled
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Handle /redirect_me
sed -i "/server_name _;$/a\ \ \ \ \ \ \ \ rewrite ^/redirect_me https://www.youtube.com/ permanent;" /etc/nginx/sites-available/default

# Start the nginx service
if [ "$(pgrep nginx)" ]; then
        service nginx restart
else
        service nginx start
fi
