#!/usr/bin/env bash
# Bash script containing commands to automatically configure a Ubuntu machine
# to respect below requirements
# 	The redirection must be a “301 Moved Permanently”

# Check for updates
 apt-get -y update

# Installs nginx
apt -y install nginx

# Changes the root page to contain the stril 'Hello World!'
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# configuring the redirect_me
sudo sed -i '/server_name _;/a \ \ \ \ \ \ \ \ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH3-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# customizing the 404
printf "Ceci n'est pas une page\n" | sudo tee /var/www/html/404.html >/dev/null
sudo sed -i '/rewrite.*/a \ \ \ \ \ \ \ \ \ error_page 404 /404.html;' /etc/nginx/sites-available/default

# Start the nginx service
service nginx start
