#!/usr/bin/env bash
# This script is used to install HAProxy to new Ubuntu server to work as a load balancer

sudo apt-get -y update
sudo apt-get -y install haproxy
# apt-get install -y --no-install-recommends software-properties-common
# add-apt-repository -y ppa:vbernat/haproxy-2.6
# apt-get install -y haproxy=2.6.\*

# Create configuration
config="

frontend main
        bind 0.0.0.0:80
	mode http
        default_backend web_servers

backend web_servers
        balance roundrobin
        option http-keep-alive
        server 493245-web-01 34.207.237.37:80 check
        server 493245-web-02 35.175.65.10:80 check

"
printf %s "$config" >> /etc/haproxy/haproxy.cfg

printf "
ENABLED=1
" >> /etc/default/haproxy

# Restart haproxy
service haproxy restart
