#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.

archive_name="$(date +"%d")-$(date +"%m")-$(date +"%Y").tar.gz"

mysqldump --all-databases -u root --password="$1" > backup.sql
tar -czvf "$archive_name" backup.sql
