#!/usr/bin/env bash
# This script creates the file myscript.pid containing its PID in /var/run dir
#+ It displays 'To infinity and beyond' indefinitely and displays
#+ 'I hate the kill command' and 'Y U no love me?!' if it receives SIGTERM and
#+ and SIGINT signal respectively
#+ It also deletes itself and terminates when receiving a SIGQUIT or SIGTERM
#+ signal.

echo $$ >> /var/run/myscript.pid

trap "echo 'I hate the kill command'; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -rf /var/run/myscript.pid; exit" SIGQUIT

until false
do 
    echo 'To infinity and beyond' 
    sleep 2
done
