#!/usr/bin/env bash
# This script displays 'To infinity and beyond' indefinetly with a
#+ sleep of 2 seconds

trap 'echo "I am invincible!!!"' SIGTERM
until false
do
    echo "To infinity and beyond"
    sleep 2
done
