#!/usr/bin/env bash
# This script displays numbers 1 to 100, Fizbuzz of multiples of 3 and 5
#+ Fizz for multiples of 3 and Buzz for muliples of 5

for ((i = 1; i <= 100; i++)); do
	if [ $((i % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Fizz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$i"
	fi
done
