#!/usr/bin/env bash
# This script displays content of /etc/passwd using while loops + IFS.

while IFS=: read -r u_name pswd u_id g_id usr_info h_dir cmd_sh; do
	echo "The user $u_name is part of the $g_id gang, lives in $h_dir and rides $cmd_sh. $u_id's place is protected by the passcode $pswd, more info about the user here: $usr_info"
done < /etc/passwd
