#!/usr/bin/env bash
#This script prints 'bad luck', 'good luck' and 'Best School' depending on the
#+ iteration number

for ((i=0; i<10; i++)); do
	if [ "$i" -eq 3 ]; then
		echo "bad luck"
	elif [ "$i" -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
done
