#!/usr/bin/env bash
#This script prints 'bad luck', 'good luck' and 'Best School' depending on the
#+ iteration number
i=0
while ((i<10)); do
	if [ "$i" -eq 3 ]; then
		echo "bad luck"
	elif [ "$i" -eq 7 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
