#!/usr/bin/env bash
#This script displays the names of files in the current directory
#+ in a list format where only ther part of the name after the first
#+ dash is displayed

for i in $(find . -type f | cut -d'-' -f2-)
do
	echo "$i"
done
