#!/usr/bin/env bash
#This script displays the names of files in the current directory
#+ in a list format where only ther part of the name after the first
#+ dash is displayed
list=$(ls)
for i in $list
do
	echo "$i" | cut -d '-' -f2
done
