#!/usr/bin/env bash
# Run nginx with nginx user and listen on port 8080
if ! grep -q "^nginx:" /etc/passwd ; then
        sudo adduser --system --no-create-home --disabled-login --group nginx
fi
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i '23i\ \n\tlisten 8080;' /etc/nginx/sites-available/default
sudo service nginx restart
