#!/usr/bin/env bash
# Run nginx with nginx user and listen on port 8080
pkill -f apache2
chmod 644 /etc/nginx/nginx.conf
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i '23i\ \tlisten 8080;' /etc/nginx/sites-available/default
sudo service nginx restart
