#!/usr/bin/env bash
# Bash script that creates an RSA key pair with private_key filename: school
# Bits for key created: 4096
# Passpharase for the key: betty
ssh-keygen -t rsa -b 4096 -f "school" -N betty
